"""Nuevos cambios

Revision ID: dde8e23a0ecc
Revises: a2e8e7112f50
Create Date: 2025-03-04 15:57:32.312960

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dde8e23a0ecc"
down_revision: Union[str, None] = "a2e8e7112f50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
