"""Nuevos cambios

Revision ID: 79f515c3d0c3
Revises: c765e68cb40f
Create Date: 2025-03-12 12:27:49.856059

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79f515c3d0c3"
down_revision: Union[str, None] = "c765e68cb40f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
