"""Nuevos cambios

Revision ID: b777afc88d7a
Revises: 969cd327e855
Create Date: 2025-03-01 16:58:38.334386

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b777afc88d7a"
down_revision: Union[str, None] = "969cd327e855"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cuentas_bancarias", sa.Column("plan_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "cuentas_bancarias",
        sa.Column(
            "fecha_inicio_plan", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "cuentas_bancarias",
        sa.Column("fecha_fin_plan", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "cuentas_bancarias",
        sa.Column("trial_activo", sa.Boolean(), nullable=True),
    )
    op.create_foreign_key(
        None, "cuentas_bancarias", "planes", ["plan_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cuentas_bancarias", type_="foreignkey")
    op.drop_column("cuentas_bancarias", "trial_activo")
    op.drop_column("cuentas_bancarias", "fecha_fin_plan")
    op.drop_column("cuentas_bancarias", "fecha_inicio_plan")
    op.drop_column("cuentas_bancarias", "plan_id")
    # ### end Alembic commands ###
