"""Nuevos cambios

Revision ID: 969cd327e855
Revises: 767f55bc427f
Create Date: 2025-03-01 16:57:23.602247

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "969cd327e855"
down_revision: Union[str, None] = "767f55bc427f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "planes", sa.Column("max_empleados", sa.Integer(), nullable=True)
    )
    op.add_column(
        "planes", sa.Column("max_sucursales", sa.Integer(), nullable=True)
    )
    op.add_column(
        "planes", sa.Column("soporte_prioritario", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "planes",
        sa.Column("uso_ilimitado_funciones", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "planes", sa.Column("duracion_dias", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("planes", "duracion_dias")
    op.drop_column("planes", "uso_ilimitado_funciones")
    op.drop_column("planes", "soporte_prioritario")
    op.drop_column("planes", "max_sucursales")
    op.drop_column("planes", "max_empleados")
    # ### end Alembic commands ###
