"""Nuevos cambios

Revision ID: 767f55bc427f
Revises: 064fe7a0fe83
Create Date: 2025-03-01 15:59:15.349328

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "767f55bc427f"
down_revision: Union[str, None] = "064fe7a0fe83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clientes", "sucursal_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("organizaciones", "nombre")
    op.alter_column(
        "proveedores", "sucursal_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "sucursales", "pais", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_index("ix_sucursal_id", table_name="sucursales")
    op.drop_constraint("sucursal_nombre_key", "sucursales", type_="unique")
    op.create_index(
        op.f("ix_sucursales_id"), "sucursales", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sucursales_id"), table_name="sucursales")
    op.create_unique_constraint(
        "sucursal_nombre_key", "sucursales", ["nombre"]
    )
    op.create_index("ix_sucursal_id", "sucursales", ["id"], unique=False)
    op.alter_column(
        "sucursales", "pais", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "proveedores",
        "sucursal_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.add_column(
        "organizaciones",
        sa.Column("nombre", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "clientes", "sucursal_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
