"""Nuevos cambios

Revision ID: 7852e9dc1bee
Revises: fc53515d9a6f
Create Date: 2025-03-02 08:47:03.442641

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7852e9dc1bee"
down_revision: Union[str, None] = "fc53515d9a6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "cuentas_bancarias_plan_id_fkey",
        "cuentas_bancarias",
        type_="foreignkey",
    )
    op.drop_column("cuentas_bancarias", "fecha_fin_plan")
    op.drop_column("cuentas_bancarias", "fecha_inicio_plan")
    op.drop_column("cuentas_bancarias", "trial_activo")
    op.drop_column("cuentas_bancarias", "plan_id")
    op.add_column(
        "organizaciones", sa.Column("plan_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "organizaciones",
        sa.Column(
            "fecha_inicio_plan", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "organizaciones",
        sa.Column("fecha_fin_plan", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "organizaciones",
        sa.Column("trial_activo", sa.Boolean(), nullable=True),
    )
    op.create_foreign_key(
        None, "organizaciones", "planes", ["plan_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "organizaciones", type_="foreignkey")
    op.drop_column("organizaciones", "trial_activo")
    op.drop_column("organizaciones", "fecha_fin_plan")
    op.drop_column("organizaciones", "fecha_inicio_plan")
    op.drop_column("organizaciones", "plan_id")
    op.add_column(
        "cuentas_bancarias",
        sa.Column("plan_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "cuentas_bancarias",
        sa.Column(
            "trial_activo", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "cuentas_bancarias",
        sa.Column(
            "fecha_inicio_plan",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "cuentas_bancarias",
        sa.Column(
            "fecha_fin_plan",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "cuentas_bancarias_plan_id_fkey",
        "cuentas_bancarias",
        "planes",
        ["plan_id"],
        ["id"],
    )
    # ### end Alembic commands ###
