"""Nuevos cambios

Revision ID: c12b9a3d123c
Revises: 79f515c3d0c3
Create Date: 2025-03-19 18:45:28.860285

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c12b9a3d123c"
down_revision: Union[str, None] = "79f515c3d0c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
