steps:
  - name: 'gcr.io/cloud-builders/docker'  # <-- 'name' PRIMERO
    id: Build
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/y-sistem/y-system-erp:$COMMIT_SHA'
      - './gestion_negocio'

  - name: 'gcr.io/cloud-builders/docker'  # <-- 'name' PRIMERO
    id: Push
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/y-sistem/y-system-erp:$COMMIT_SHA'

  - name: 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/y-sistem/y-system-erp:$COMMIT_SHA'  # <-- 'name' PRIMERO
    id: Migrate
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "Current working directory: $(pwd)"
        cd /app
        echo "New working directory: $(pwd)"
        echo "Files in /app:"
        ls -la /app
        echo "Trying to run alembic:"
        whoami
        alembic -c alembic.ini upgrade head  # <-- Ruta relativa correcta.
        echo "Exit code: $?"

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'  # <-- 'name' PRIMERO
    id: Deploy
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'y-system-erp'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/y-sistem/y-system-erp:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--service-account'
      - '130051245707-compute@developer.gserviceaccount.com'
      - '--port=8080'
      - '--vpc-connector=projects/y-sistem/locations/us-central1/connectors/conector-erp'
      - '--add-cloudsql-instances=y-sistem:us-central1:y-system-db'
      - '--set-env-vars=DATABASE_URL=postgresql+asyncpg://postgres:postgres@unix:///cloudsql/y-sistem:us-central1:y-system-db/.s.PGSQL.5432/ysistemdb'
      - '--allow-unauthenticated'


options:
  logging: CLOUD_LOGGING_ONLY