steps:
  - name: 'python:3.11-slim'
    entrypoint: bash
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y wget
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy
        ./cloud_sql_proxy -instances="y-sistem:us-central1:y-system-version-1=tcp:5432" &
        sleep 5

        pip install alembic pg8000
        cd gestion_negocio  # Asegúrate de que este directorio exista. Usa un Dockerfile si es necesario.

        export CLOUD_SQL_CONNECTION_NAME="y-sistem:us-central1:y-system-version-1"
        export DB_USER="postgres"
        export DB_NAME="postgres"
        alembic upgrade head
    secretEnv: ['DB_PASSWORD']

availableSecrets:
  secretManager:
  - versionName: projects/PROJECT/secrets/DB_PASSWORD_y-system-version-1/versions/1  # Reemplaza PROJECT y la versión.
    env: 'DB_PASSWORD'

# serviceAccount:  <-- ¡NO INCLUYAS ESTA LÍNEA si usas la cuenta predeterminada!
logsBucket: 'gs://y-sistem_cloudbuild'

options:
    logging: CLOUD_LOGGING_ONLY #Opcional, pero recomendado