steps:
  - name: 'python:3.11-slim'
    entrypoint: bash
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y wget
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy
        ./cloud_sql_proxy -instances="y-sistem:us-central1:y-system-version-1=tcp:5432" &
        sleep 5

        pip install alembic pg8000 python-dotenv
        cd gestion_negocio

        export CLOUD_SQL_CONNECTION_NAME="y-sistem:us-central1:y-system-version-1"
        export DB_USER="postgres"
        export DB_NAME="postgres"
        alembic upgrade head
    secretEnv: ['DB_PASSWORD']

availableSecrets:
  secretManager:
  - versionName: projects/y-sistem/secrets/DB_PASSWORD_y-system-version-1/versions/1  # Reemplaza PROJECT y la versión.
    env: 'DB_PASSWORD'

# serviceAccount:  <-- Sin serviceAccount si usas la predeterminada.
logsBucket: 'gs://y-sistem_cloudbuild'

options:
  logging: GCS_ONLY  # Guarda los logs *solo* en el bucket.