steps:
  # 1) Build la imagen
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/y-sistem/y-system-erp:$COMMIT_SHA
      - ./gestion_negocio

  # 2) Push
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/y-sistem/y-system-erp:$COMMIT_SHA

  # 3) Crear o actualizar el Job "db-migrations"
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Create-Job'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Borramos si existe, para recrearlo limpio:
        gcloud run jobs delete db-migrations --region=us-central1 --quiet || true

        # Creamos el Job
        gcloud run jobs create db-migrations \
          --image us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/y-sistem/y-system-erp:$COMMIT_SHA \
          --region us-central1 \
          --set-env-vars DATABASE_URL='postgresql+pg8000://postgres:postgres@/ysistemdb?unix_sock=/cloudsql/y-sistem:us-central1:y-system-version-1/.s.PGSQL.5432' \
          --add-cloudsql-instances y-sistem:us-central1:y-system-version-1 \
          --service-account 130051245707-compute@developer.gserviceaccount.com \
          --command 'alembic' \
          --args 'upgrade,head'

  # 4) Ejecutar el Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Execute-Job'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Ejecutando migraciones..."
        gcloud run jobs execute db-migrations --region=us-central1 --wait
        echo "¡Migraciones completadas!"

  # 5) Deploy del servicio
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy-Service'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - y-system-erp
      - --image
      - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/y-sistem/y-system-erp:$COMMIT_SHA
      - --region=us-central1
      - --service-account=130051245707-compute@developer.gserviceaccount.com
      - --port=8080
      - --vpc-connector=projects/y-sistem/locations/us-central1/connectors/conector-erp
      - --add-cloudsql-instances=y-sistem:us-central1:y-system-version-1
      - --set-env-vars=DATABASE_URL=postgresql+asyncpg://postgres:postgres@unix:///cloudsql/y-sistem:us-central1:y-system-version-1/.s.PGSQL.5432/ysistemdb
      - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  # Esto para que recoja COMMIT_SHA si gustas
  _COMMIT_SHA: $COMMIT_SHA
