from .auth import router as auth_router
from .clientes import router as clientes_router
from .proveedores import router as clientes_router
from .empleados import router as empleados_router
from .productos import router as productos_router
from .ventas import router as ventas_router
from .tesoreria import router as tesoreria_router
from .cuentas_wallet import router as cuentas_wallet_router
from .chats import router as chats_router
